import 'package:tuple/tuple.dart';

List smileyList = [
  Tuple2('Grinning Face', '😀'),
  Tuple2('Grinning Face With Big Eyes', '😃'),
  Tuple2('Grinning Face With Smiling Eyes', '😄'),
  Tuple2('Beaming Face With Smiling Eyes', '😁'),
  Tuple2('Grinning Squinting Face', '😆'),
  Tuple2('Grinning Face With Sweat', '😅'),
  Tuple2('Rolling on the Floor Laughing', '🤣'),
  Tuple2('Face With Tears of Joy', '😂'),
  Tuple2('Slightly Smiling Face', '🙂'),
  Tuple2('Upside-Down Face', '🙃'),
  Tuple2('Winking Face', '😉'),
  Tuple2('Smiling Face With Smiling Eyes', '😊'),
  Tuple2('Smiling Face With Halo', '😇'),
  Tuple2('Smiling Face With Hearts', '🥰'),
  Tuple2('Smiling Face With Heart-Eyes', '😍'),
  Tuple2('Star-Struck', '🤩'),
  Tuple2('Face Blowing a Kiss', '😘'),
  Tuple2('Kissing Face', '😗'),
  Tuple2('Smiling Face', '☺'),
  Tuple2('Kissing Face With Closed Eyes', '😚'),
  Tuple2('Kissing Face With Smiling Eyes', '😙'),
  Tuple2('Face Savoring Food', '😋'),
  Tuple2('Face With Tongue', '😛'),
  Tuple2('Winking Face With Tongue', '😜'),
  Tuple2('Zany Face', '🤪'),
  Tuple2('Squinting Face With Tongue', '😝'),
  Tuple2('Money-Mouth Face', '🤑'),
  Tuple2('Hugging Face', '🤗'),
  Tuple2('Face With Hand Over Mouth', '🤭'),
  Tuple2('Shushing Face', '🤫'),
  Tuple2('Thinking Face', '🤔'),
  Tuple2('Zipper-Mouth Face', '🤐'),
  Tuple2('Face With Raised Eyebrow', '🤨'),
  Tuple2('Neutral Face', '😐'),
  Tuple2('Expressionless Face', '😑'),
  Tuple2('Face Without Mouth', '😶'),
  Tuple2('Smirking Face', '😏'),
  Tuple2('Unamused Face', '😒'),
  Tuple2('Face With Rolling Eyes', '🙄'),
  Tuple2('Grimacing Face', '😬'),
  Tuple2('Lying Face', '🤥'),
  Tuple2('Relieved Face', '😌'),
  Tuple2('Pensive Face', '😔'),
  Tuple2('Sleepy Face', '😪'),
  Tuple2('Drooling Face', '🤤'),
  Tuple2('Sleeping Face', '😴'),
  Tuple2('Face With Medical Mask', '😷'),
  Tuple2('Face With Thermometer', '🤒'),
  Tuple2('Face With Head-Bandage', '🤕'),
  Tuple2('Nauseated Face', '🤢'),
  Tuple2('Face Vomiting', '🤮'),
  Tuple2('Sneezing Face', '🤧'),
  Tuple2('Hot Face', '🥵'),
  Tuple2('Cold Face', '🥶'),
  Tuple2('Woozy Face', '🥴'),
  Tuple2('Dizzy Face', '😵'),
  Tuple2('Exploding Head', '🤯'),
  Tuple2('Cowboy Hat Face', '🤠'),
  Tuple2('Partying Face', '🥳'),
  Tuple2('Smiling Face With Sunglasses', '😎'),
  Tuple2('Nerd Face', '🤓'),
  Tuple2('Face With Monocle', '🧐'),
  Tuple2('Confused Face', '😕'),
  Tuple2('Worried Face', '😟'),
  Tuple2('Slightly Frowning Face', '🙁'),
  Tuple2('Frowning Face', '☹\ufe0f'),
  Tuple2('Face With Open Mouth', '\ud83d\udea3'),
  Tuple2('Hushed Face', '😯'),
  Tuple2('Astonished Face', '😲'),
  Tuple2('Flushed Face', '😳'),
  Tuple2('Pleading Face', '🥺'),
  Tuple2('Frowning Face With Open Mouth', '😦'),
  Tuple2('Anguished Face', '😧'),
  Tuple2('Fearful Face', '😨'),
  Tuple2('Anxious Face With Sweat', '😰'),
  Tuple2('Sad but Relieved Face', '😥'),
  Tuple2('Crying Face', '😢'),
  Tuple2('Loudly Crying Face', '😭'),
  Tuple2('Face Screaming in Fear', '😱'),
  Tuple2('Confounded Face', '😖'),
  Tuple2('Persevering Face', '😣'),
  Tuple2('Disappointed Face', '😞'),
  Tuple2('Downcast Face With Sweat', '😓'),
  Tuple2('Weary Face', '😩'),
  Tuple2('Tired Face', '😫'),
  Tuple2('Face With Steam From Nose', '😤'),
  Tuple2('Pouting Face', '😡'),
  Tuple2('Angry Face', '😠'),
  Tuple2('Face With Symbols on Mouth', '🤬'),
  Tuple2('Smiling Face With Horns', '😈'),
  Tuple2('Angry Face With Horns', '👿'),
  Tuple2('Skull', '💀'),
  Tuple2('Skull and Crossbones', '☠'),
  Tuple2('Pile of Poo', '💩'),
  Tuple2('Clown Face', '🤡'),
  Tuple2('Ogre', '👹'),
  Tuple2('Goblin', '👺'),
  Tuple2('Ghost', '👻'),
  Tuple2('Alien', '👽'),
  Tuple2('Alien Monster', '👾'),
  Tuple2('Robot Face', '🤖'),
  Tuple2('Grinning Cat Face', '😺'),
  Tuple2('Grinning Cat Face With Smiling Eyes', '😸'),
  Tuple2('Cat Face With Tears of Joy', '😹'),
  Tuple2('Smiling Cat Face With Heart-Eyes', '😻'),
  Tuple2('Cat Face With Wry Smile', '😼'),
  Tuple2('Kissing Cat Face', '😽'),
  Tuple2('Weary Cat Face', '🙀'),
  Tuple2('Crying Cat Face', '😿'),
  Tuple2('Pouting Cat Face', '😾'),
  Tuple2('Kiss Mark', '💋'),
  Tuple2('Waving Hand', '👋'),
  Tuple2('Raised Back of Hand', '🤚'),
  Tuple2('Hand With Fingers Splayed', '🖐'),
  Tuple2('Raised Hand', '✋'),
  Tuple2('Vulcan Salute', '🖖'),
  Tuple2('OK Hand', '👌'),
  Tuple2('Victory Hand', '✌'),
  Tuple2('Crossed Fingers', '🤞'),
  Tuple2('Love-You Gesture', '🤟'),
  Tuple2('Sign of the Horns', '🤘'),
  Tuple2('Call Me Hand', '🤙'),
  Tuple2('Backhand Index Pointing Left', '👈'),
  Tuple2('Backhand Index Pointing Right', '👉'),
  Tuple2('Backhand Index Pointing Up', '👆'),
  Tuple2('Middle Finger', '🖕'),
  Tuple2('Backhand Index Pointing Down', '👇'),
  Tuple2('Index Pointing Up', '☝'),
  Tuple2('Thumbs Up', '👍'),
  Tuple2('Thumbs Down', '👎'),
  Tuple2('Raised Fist', '✊'),
  Tuple2('Oncoming Fist', '👊'),
  Tuple2('Left-Facing Fist', '🤛'),
  Tuple2('Right-Facing Fist', '🤜'),
  Tuple2('Clapping Hands', '👏'),
  Tuple2('Raising Hands', '🙌'),
  Tuple2('Open Hands', '👐'),
  Tuple2('Palms Up Together', '🤲'),
  Tuple2('Handshake', '🤝'),
  Tuple2('Folded Hands', '🙏'),
  Tuple2('Writing Hand', '✍'),
  Tuple2('Nail Polish', '💅'),
  Tuple2('Selfie', '🤳'),
  Tuple2('Flexed Biceps', '💪'),
  Tuple2('Leg', '🦵'),
  Tuple2('Foot', '🦶'),
  Tuple2('Ear', '👂'),
  Tuple2('Nose', '👃'),
  Tuple2('Brain', '🧠'),
  Tuple2('Tooth', '🦷'),
  Tuple2('Bone', '🦴'),
  Tuple2('Eyes', '👀'),
  Tuple2('Eye', '👁'),
  Tuple2('Tongue', '👅'),
  Tuple2('Mouth', '👄'),
  Tuple2('Baby', '👶'),
  Tuple2('Child', '🧒'),
  Tuple2('Boy', '👦'),
  Tuple2('Girl', '👧'),
  Tuple2('Person', '🧑'),
  Tuple2('Man', '👨'),
  Tuple2('Man: Beard', '🧔'),
  Tuple2('Man: Blond Hair', '👱\u200d♂️'),
  Tuple2('Man: Red Hair', '👨\u200d🦰'),
  Tuple2('Man: Curly Hair', '👨\u200d🦱'),
  Tuple2('Man: White Hair', '👨\u200d🦳'),
  Tuple2('Man: Bald', '👨\u200d🦲'),
  Tuple2('Woman', '👩'),
  Tuple2('Woman: Blond Hair', '👱\u200d♀️'),
  Tuple2('Woman: Red Hair', '👩\u200d🦰'),
  Tuple2('Woman: Curly Hair', '👩\u200d🦱'),
  Tuple2('Woman: White Hair', '👩\u200d🦳'),
  Tuple2('Woman: Bald', '👩\u200d🦲'),
  Tuple2('Older Person', '🧓'),
  Tuple2('Old Man', '👴'),
  Tuple2('Old Woman', '👵'),
  Tuple2('Man Frowning', '🙍\u200d♂️'),
  Tuple2('Woman Frowning', '🙍\u200d♀️'),
  Tuple2('Man Pouting', '🙎\u200d♂️'),
  Tuple2('Woman Pouting', '🙎\u200d♀️'),
  Tuple2('Man Gesturing No', '🙅\u200d♂️'),
  Tuple2('Woman Gesturing No', '🙅\u200d♀️'),
  Tuple2('Man Gesturing OK', '🙆\u200d♂️'),
  Tuple2('Woman Gesturing OK', '🙆\u200d♀️'),
  Tuple2('Man Tipping Hand', '💁\u200d♂️'),
  Tuple2('Woman Tipping Hand', '💁\u200d♀️'),
  Tuple2('Man Raising Hand', '🙋\u200d♂️'),
  Tuple2('Woman Raising Hand', '🙋\u200d♀️'),
  Tuple2('Man Bowing', '🙇\u200d♂️'),
  Tuple2('Woman Bowing', '🙇\u200d♀️'),
  Tuple2('Man Facepalming', '🤦\u200d♂️'),
  Tuple2('Woman Facepalming', '🤦\u200d♀️'),
  Tuple2('Man Shrugging', '🤷\u200d♂️'),
  Tuple2('Woman Shrugging', '🤷\u200d♀️'),
  Tuple2('Man Health Worker', '👨\u200d⚕️'),
  Tuple2('Woman Health Worker', '👩\u200d⚕️'),
  Tuple2('Man Student', '👨\u200d🎓'),
  Tuple2('Woman Student', '👩\u200d🎓'),
  Tuple2('Man Teacher', '👨\u200d🏫'),
  Tuple2('Woman Teacher', '👩\u200d🏫'),
  Tuple2('Man Judge', '👨\u200d⚖️'),
  Tuple2('Woman Judge', '👩\u200d⚖️'),
  Tuple2('Man Farmer', '👨\u200d🌾'),
  Tuple2('Woman Farmer', '👩\u200d🌾'),
  Tuple2('Man Cook', '👨\u200d🍳'),
  Tuple2('Woman Cook', '👩\u200d🍳'),
  Tuple2('Man Mechanic', '👨\u200d🔧'),
  Tuple2('Woman Mechanic', '👩\u200d🔧'),
  Tuple2('Man Factory Worker', '👨\u200d🏭'),
  Tuple2('Woman Factory Worker', '👩\u200d🏭'),
  Tuple2('Man Office Worker', '👨\u200d💼'),
  Tuple2('Woman Office Worker', '👩\u200d💼'),
  Tuple2('Man Scientist', '👨\u200d🔬'),
  Tuple2('Woman Scientist', '👩\u200d🔬'),
  Tuple2('Man Technologist', '👨\u200d💻'),
  Tuple2('Woman Technologist', '👩\u200d💻'),
  Tuple2('Man Singer', '👨\u200d🎤'),
  Tuple2('Woman Singer', '👩\u200d🎤'),
  Tuple2('Man Artist', '👨\u200d🎨'),
  Tuple2('Woman Artist', '👩\u200d🎨'),
  Tuple2('Man Pilot', '👨\u200d✈️'),
  Tuple2('Woman Pilot', '👩\u200d✈️'),
  Tuple2('Man Astronaut', '👨\u200d🚀'),
  Tuple2('Woman Astronaut', '👩\u200d🚀'),
  Tuple2('Man Firefighter', '👨\u200d🚒'),
  Tuple2('Woman Firefighter', '👩\u200d🚒'),
  Tuple2('Man Police Officer', '👮\u200d♂️'),
  Tuple2('Woman Police Officer', '👮\u200d♀️'),
  Tuple2('Man Detective', '🕵️\u200d♂️'),
  Tuple2('Woman Detective', '🕵️\u200d♀️'),
  Tuple2('Man Guard', '💂\u200d♂️'),
  Tuple2('Woman Guard', '💂\u200d♀️'),
  Tuple2('Man Construction Worker', '👷\u200d♂️'),
  Tuple2('Woman Construction Worker', '👷\u200d♀️'),
  Tuple2('Prince', '🤴'),
  Tuple2('Princess', '👸'),
  Tuple2('Man Wearing Turban', '👳\u200d♂️'),
  Tuple2('Woman Wearing Turban', '👳\u200d♀️'),
  Tuple2('Man With Chinese Cap', '👲'),
  Tuple2('Woman With Headscarf', '🧕'),
  Tuple2('Man in Tuxedo', '🤵'),
  Tuple2('Bride With Veil', '👰'),
  Tuple2('Pregnant Woman', '🤰'),
  Tuple2('Breast-Feeding', '🤱'),
  Tuple2('Baby Angel', '👼'),
  Tuple2('Santa Claus', '🎅'),
  Tuple2('Mrs. Claus', '🤶'),
  Tuple2('Man Superhero', '🦸\u200d♂️'),
  Tuple2('Woman Superhero', '🦸\u200d♀️'),
  Tuple2('Man Supervillain', '🦹\u200d♂️'),
  Tuple2('Woman Supervillain', '🦹\u200d♀️'),
  Tuple2('Man Mage', '🧙\u200d♂️'),
  Tuple2('Woman Mage', '🧙\u200d♀️'),
  Tuple2('Man Fairy', '🧚\u200d♂️'),
  Tuple2('Woman Fairy', '🧚\u200d♀️'),
  Tuple2('Man Vampire', '🧛\u200d♂️'),
  Tuple2('Woman Vampire', '🧛\u200d♀️'),
  Tuple2('Merman', '🧜\u200d♂️'),
  Tuple2('Mermaid', '🧜\u200d♀️'),
  Tuple2('Man Elf', '🧝\u200d♂️'),
  Tuple2('Woman Elf', '🧝\u200d♀️'),
  Tuple2('Man Genie', '🧞\u200d♂️'),
  Tuple2('Woman Genie', '🧞\u200d♀️'),
  Tuple2('Man Zombie', '🧟\u200d♂️'),
  Tuple2('Woman Zombie', '🧟\u200d♀️'),
  Tuple2('Man Getting Massage', '💆\u200d♂️'),
  Tuple2('Woman Getting Massage', '💆\u200d♀️'),
  Tuple2('Man Getting Haircut', '💇\u200d♂️'),
  Tuple2('Woman Getting Haircut', '💇\u200d♀️'),
  Tuple2('Man Walking', '🚶\u200d♂️'),
  Tuple2('Woman Walking', '🚶\u200d♀️'),
  Tuple2('Man Running', '🏃\u200d♂️'),
  Tuple2('Woman Running', '🏃\u200d♀️'),
  Tuple2('Woman Dancing', '💃'),
  Tuple2('Man Dancing', '🕺'),
  Tuple2('Man in Suit Levitating', '🕴'),
  Tuple2('Men With Bunny Ears', '👯\u200d♂️'),
  Tuple2('Women With Bunny Ears', '👯\u200d♀️'),
  Tuple2('Man in Steamy Room', '🧖\u200d♂️'),
  Tuple2('Woman in Steamy Room', '🧖\u200d♀️'),
  Tuple2('Person in Lotus Position', '🧘'),
  Tuple2('Women Holding Hands', '👭'),
  Tuple2('Woman and Man Holding Hands', '👫'),
  Tuple2('Men Holding Hands', '👬'),
  Tuple2('Kiss', '💏'),
  Tuple2('Kiss: Man, Man', '👨\u200d❤️\u200d💋\u200d👨'),
  Tuple2('Kiss: Woman, Woman', '👩\u200d❤️\u200d💋\u200d👩'),
  Tuple2('Couple With Heart', '💑'),
  Tuple2('Couple With Heart: Man, Man', '👨\u200d❤️\u200d👨'),
  Tuple2('Couple With Heart: Woman, Woman', '👩\u200d❤️\u200d👩'),
  Tuple2('Family', '👪'),
  Tuple2('Family: Man, Woman, Boy', '👨\u200d👩\u200d👦'),
  Tuple2('Family: Man, Woman, Girl', '👨\u200d👩\u200d👧'),
  Tuple2('Family: Man, Woman, Girl, Boy', '👨\u200d👩\u200d👧\u200d👦'),
  Tuple2('Family: Man, Woman, Boy, Boy', '👨\u200d👩\u200d👦\u200d👦'),
  Tuple2('Family: Man, Woman, Girl, Girl', '👨\u200d👩\u200d👧\u200d👧'),
  Tuple2('Family: Man, Man, Boy', '👨\u200d👨\u200d👦'),
  Tuple2('Family: Man, Man, Girl', '👨\u200d👨\u200d👧'),
  Tuple2('Family: Man, Man, Girl, Boy', '👨\u200d👨\u200d👧\u200d👦'),
  Tuple2('Family: Man, Man, Boy, Boy', '👨\u200d👨\u200d👦\u200d👦'),
  Tuple2('Family: Man, Man, Girl, Girl', '👨\u200d👨\u200d👧\u200d👧'),
  Tuple2('Family: Woman, Woman, Boy', '👩\u200d👩\u200d👦'),
  Tuple2('Family: Woman, Woman, Girl', '👩\u200d👩\u200d👧'),
  Tuple2('Family: Woman, Woman, Girl, Boy', '👩\u200d👩\u200d👧\u200d👦'),
  Tuple2('Family: Woman, Woman, Boy, Boy', '👩\u200d👩\u200d👦\u200d👦'),
  Tuple2('Family: Woman, Woman, Girl, Girl', '👩\u200d👩\u200d👧\u200d👧'),
  Tuple2('Family: Man, Boy', '👨\u200d👦'),
  Tuple2('Family: Man, Boy, Boy', '👨\u200d👦\u200d👦'),
  Tuple2('Family: Man, Girl', '👨\u200d👧'),
  Tuple2('Family: Man, Girl, Boy', '👨\u200d👧\u200d👦'),
  Tuple2('Family: Man, Girl, Girl', '👨\u200d👧\u200d👧'),
  Tuple2('Family: Woman, Boy', '👩\u200d👦'),
  Tuple2('Family: Woman, Boy, Boy', '👩\u200d👦\u200d👦'),
  Tuple2('Family: Woman, Girl', '👩\u200d👧'),
  Tuple2('Family: Woman, Girl, Boy', '👩\u200d👧\u200d👦'),
  Tuple2('Family: Woman, Girl, Girl', '👩\u200d👧\u200d👧'),
  Tuple2('Speaking Head', '🗣'),
  Tuple2('Bust in Silhouette', '👤'),
  Tuple2('Busts in Silhouette', '👥'),
  Tuple2('Footprints', '👣'),
  Tuple2('Luggage', '🧳'),
  Tuple2('Closed Umbrella', '🌂'),
  Tuple2('Umbrella', '☂'),
  Tuple2('Thread', '🧵'),
  Tuple2('Yarn', '🧶'),
  Tuple2('Glasses', '👓'),
  Tuple2('Sunglasses', '🕶'),
  Tuple2('Goggles', '🥽'),
  Tuple2('Lab Coat', '🥼'),
  Tuple2('Necktie', '👔'),
  Tuple2('T-Shirt', '👕'),
  Tuple2('Jeans', '👖'),
  Tuple2('Scarf', '🧣'),
  Tuple2('Gloves', '🧤'),
  Tuple2('Coat', '🧥'),
  Tuple2('Socks', '🧦'),
  Tuple2('Dress', '👗'),
  Tuple2('Kimono', '👘'),
  Tuple2('Bikini', '👙'),
  Tuple2('Woman’s Clothes', '👚'),
  Tuple2('Purse', '👛'),
  Tuple2('Handbag', '👜'),
  Tuple2('Clutch Bag', '👝'),
  Tuple2('Backpack', '🎒'),
  Tuple2('Man’s Shoe', '👞'),
  Tuple2('Running Shoe', '👟'),
  Tuple2('Hiking Boot', '🥾'),
  Tuple2('Flat Shoe', '🥿'),
  Tuple2('High-Heeled Shoe', '👠'),
  Tuple2('Woman’s Sandal', '👡'),
  Tuple2('Woman’s Boot', '👢'),
  Tuple2('Crown', '👑'),
  Tuple2('Woman’s Hat', '👒'),
  Tuple2('Top Hat', '🎩'),
  Tuple2('Graduation Cap', '🎓'),
  Tuple2('Billed Cap', '🧢'),
  Tuple2('Rescue Worker’s Helmet', '⛑'),
  Tuple2('Lipstick', '💄'),
  Tuple2('Ring', '💍'),
  Tuple2('Briefcase', '💼')
];